### ISSUE TITLE
Dynamically update OC member count on OC website

### ISSUE THREAD

**Issue by calincionca35** [OperationCode/front-end#1019]
# Feature request

OC member count on OC website is a rough estimate because it is hard coded. 
## Proposed solution

It would be nice to have a dynamic updating of current member count on OC website by retrieving this information from OC Slack API.

**Comment by tristinDLC** [comment]
I haven't looking into their current methodology, but the last I looked when doing something similar for another Slack team I belong to, you'd have to query `user.list` to get a total list of users and then count that list to return a total number of members. I don't think there is an actual attribute for just purely returning a member count. So we should probably use #general for the channel to query since every new member is added there by default. 

Last I heard though, it was coming down the pipeline that lists were going to be truncated at like 1500 or 2000 or something. I know we're over 6k members strong as this point, so it won't be too helpful querying `user.list` anymore as we well exceed that truncated limit easily.

**Comment by ivanmartinezmorales** [comment]
When you're talking about the number of members, are you referring to the number of members on the `/who_we_serve` page? I see what you're saying about the value being hard coded. It would be nice to have this value become a dynamic value over having it hard coded. 

And while I agree the Slack API would be a great avenue to pursue this solution, I think that requires implementing `state` into our component. 

At first glance, adding state seems like it would be an anti-pattern here. Any ideas on what the best approach would be here? @kylemh @tristinDLC 🤔

**Comment by ivanmartinezmorales** [comment]
Also on the subject of fetching data: would a more sustainable solution moving forward be implementing a store? Or could we expose an endpoint in the op-code backend service? I might be getting far too ahead of myself here.

**Comment by kylemh** [comment]
We could expose an endpoint from OC back-end, but we're trying to tie it to our Slack instance instead. Did you read @tristinDLC's post?

**Comment by ivanmartinezmorales** [comment]
I did. I understand what he’s saying, as far as wiring into the component, how would you prefer we go about it? Where would we make the request to the Slack API? In `who_we_serve.js`? Or do we have an instance of a redux store somewhere? Also does OC already have a provisioned Slack API key?

Don’t mean to overcomplicate things, I would just like to enumerate the potential solutions and which solution would be best into the future. At least from my understanding

**Comment by kylemh** [comment]
Yeah, making that call either on the client or in getInitialProps (server render lifecycle for Next.js) should work. Are you on Slack? DM me and I’ll send a token to use and also put it into CI. Please ensure you don’t check it in 🙏

**Comment by ivanmartinezmorales** [comment]
Sweet, I'll ping you on Slack. I'll triple check that I leave it out!

**Comment by ivanmartinezmorales** [comment]
Morning everyone, I went ahead and implemented that method in my fork. Let me know your thoughts/comments/suggestions: [here](https://github.com/ivanmartinezmorales/front-end/blob/31eb398ec6feb8b83dbb96c2faeebc2b9ea20db0/pages/who_we_serve.js#L144-L163)
