### ISSUE TITLE
Resources page doesn't always show resources even when they exist

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/front-end#1160]
# Bug Report
## What is the current behavior?
Sometimes when there are indeed resources available, the page shows "This search yielded no results. Try searching for something else." Example: https://operationcode.org/resources/1?q=devhints

## What is the expected behavior?
When there are resources available, the page should show those resources

## What steps did you take to get this behavior?
Go to https://operationcode.org/resources and type in `devhints` in the search field. It will say there are no results, yet if you look at the response from the Resources API for https://resources.operationcode.org/api/v1/search/?page=0&q=devhints, you'll see that there is a result for this search.

### Operating System
N/A
### Browser
N/A
### Is This A Third-Party Issue?

N/A
### Screenshots

<img width="950" alt="Screen Shot 2020-07-05 at 9 42 30 PM" src="https://user-images.githubusercontent.com/2008701/86550754-ddcc0380-bf08-11ea-90bc-d02b5b5f9f84.png">

**Comment by manthonyg** [comment]
When I recreate this it is actually showing the error for ANYTHING I use the search input to search.

**Comment by manthonyg** [comment]
So I looked through this and I found at least one of the problems:

In [#1140](https://github.com/OperationCode/front-end/pull/1140) I did a hotfix to make sure it was querying for `page 0` if using the search endpoint. What I missed is this line... 

`if (fetchedResources.length === 0 || fetchedNumberOfPages === 0)`

...will throw an error because it assumes there were no resources returned whenever `fetchedNumberOfPages` is `0`.. which it always will be when using search endpoint. 

The expected response schema for search endpoint should include a `number_of_pages` field according to our currents doc will include a field:

  `"number_of_pages": <number of pages returned>`

...but I am not getting this in any query that uses the search endpoint. I use this to feed to the pagination component, but since it has a default value of `0` it is always such (will only return a single page of results for searches using search endpoint). To my knowledge this is new behavior and probably at least one of the reasons we having issues with resources now. Can you replicate this @aaron-suarez or am I going crazy?

**Comment by aaron-suarez** [comment]
You're right @manthonyg, for some reason the API is no longer returning `number_of_pages` and it should be. The only thing I can think of is that we recently bumped the algolia library to a newer version. Perhaps something changed with it and that broke. I'll dig in deeper today and find out for sure.

Side note, I suspected that our unit tests around `/search` weren't doing anything and I think this confirms that's true because the missing attribute `number_of_pages` should have been caught by the unit tests. If possible, I'm going to fix that too.

Thanks for investigating!

**Comment by aaron-suarez** [comment]
@mike-lloyd03 we introduced this when we did https://github.com/OperationCode/resources_api/pull/340 because we missed the change from `pagination_details` to `details` on the search endpoint:

https://github.com/OperationCode/resources_api/blob/main/app/api/routes/search.py#L75

I knew that those unit tests for the search endpoint were faulty, this definitely should have been caught. @mike-lloyd03 do you want to do the PR to fix it or just review one that I'll open up?

**Comment by mike-lloyd03** [comment]
I can take it. I should have some time tonight to take a look.

**Comment by aaron-suarez** [comment]
Ok great! Try to see about why the unit tests for `search` didn't catch it and fix that too. If you have any trouble or need anything hit me up on slack, I should be available tonight

**Comment by aaron-suarez** [comment]
Fixed in https://github.com/OperationCode/resources_api/pull/345 which has been deployed to production.
