### ISSUE TITLE
Add GuideStar logo on the donate page

### ISSUE THREAD

**Issue by Lianis-Operations** [OperationCode/front-end#1393]
# Feature request
- Add Guidestar logo to Donate page.
- Assess best location to put Guidestar logo in footer.
- The Seal should have an embedded URL to the guidestar.org site.
- URL: https://www.guidestar.org/
![guidestar-gold-seal-2021-rgb](https://user-images.githubusercontent.com/51661129/108640355-749a0000-7499-11eb-89af-4fdb6efaff97.gif)

**Comment by hollomancer** [comment]
@Lianis-Operations, can you add the Guidestar image and URL to this issue?

**Comment by kylemh** [comment]
She asked me, and I suggested she leave it to me so I can optimize/size/upload to S3.

**Comment by Lianis-Operations** [comment]
@hollomancer Done!
@kylemh It's the same image Cynthia sent via email.

**Comment by calincionca35** [comment]
I would like to work on this issue.

**Comment by hollomancer** [comment]
Adding copy; 

Thank you for reaching out and asking about Operation Code's fundraising efforts. At the current time, all donations have been going to support the following programs and initiatives:
Ongoing monthly operational costs such as our AWS server and SaaS for data hosting, project management and programming
3rd party Slack integration applications
Open source software on Github, including Hackathon fees for participation
Meetup fees for chapter events
Educational licenses such as Team Treehouse, A Cloud Guru, Secure Code Warrior
Part-time staff salary (2 roles) for administrative and tax needs and operational support
In addition, here are upcoming programs we are building and need ongoing funding to provide for our members. As you may know, 98% of Operation Code is run by volunteers, who often work one or two jobs. In order to provide more value to members, we would like to implement the following:
Paid Community Manager, Communications and Fundraising roles for ongoing stewardship and sponsorship outreach, member support, event support, case management and resource coordination with partnering agencies to provide holistic services not limited to: mental-health, housing support, food and heat insecurity issues, public advocacy (for increased VET TEC and educational funding at the policy level)
Operation Code Transition Assistance Program (OCTAP) is currently in the active planning stage. We need ongoing paid instructors for service continuity for this program to succeed
Our Slack platform is currently on a grandfathered plan for non-profits, but now that Slack has been bought out by Salesforce, other non-profits are starting to see charges per member use. This will affect our operational ability without funding to support
Ongoing paid educational licenses, sponsored events, guest keynote speakers and other key resources for members to learn, grow, and receive hands-on assistance to meet our mission
Operation Code is growing at am average rate of 33% every year. Without your support, we will not succeed in meeting our mission to get more transitioning military, veterans and military spouses into the tech industry, and continue to stay in the industry and grow.  We want to be able to raise the bar on serving our members with more programs, resources and benefits, however, we need your continued help. Will you join us?

**Comment by hollomancer** [comment]
From Cyn (actually, should this be a separate ticket?)

**Comment by datphotogurl** [comment]
Yes @hollomancer please make the new content a separate ticket so @Lianis-Operations can close this out.

**Comment by hollomancer** [comment]
Okay. Creating a new ticket - @Lianis-Operations to close this.
