### ISSUE TITLE
Replace Modal Component with Radix UI's Dialog

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#1510]
We have and use a Modal component in a few places.

No real issues with `react-modal` that I'm aware of, but I'd rather use Radix for most/all primitives.

This ticket is to replace our Modal component and re-implement a styled instance of [Radix UI's Dialog](https://www.radix-ui.com/docs/primitives/components/dialog) and update any stories and integration tests. Feel free to remove unit tests.

**Comment by florahon** [comment]
Hi! May I work on this issue?

**Comment by kylemh** [comment]
Absolutely!

**Comment by florahon** [comment]
Hi - sorry it took me so long to get started on this! I had a quick question - is the goal to replace each instance of the Modal shared component with the Radix Dialog, or to replace the actual ReactModal within the shared component with a Dialog instance? (I was assuming the latter, but was running into some trouble since it seems kind of different implementation-wise, so just wanted to check.) Thanks!

**Comment by florahon** [comment]
Hi again! So I'm running into a weird issue where the "join" Cypress tests are failing on GitHub, but all the tests are passing locally. I don't think anything I modified in this PR relates to the account registration so I'm not really sure why it's failing - would you happen to have any tips? Thanks!
