### ISSUE TITLE
Button component accessibility

### ISSUE THREAD

**Issue by dirtyredz** [OperationCode/front-end#198]
# Feature
Button component needs accessibility

## Why is this feature being added?
Accessibility is very important!

## What should your feature do?
Accept aria props.
Handle "onKeyPress" the same as "onClick"

**Comment by kylemh** [comment]
I love that you care about accessibility. [As you can see](https://github.com/OperationCode/operationcode_frontend/issues/566), we have a lot to improve on the live site.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

Unless there's a clear need for ARIA attributes (we depart from semantic HTML), I think we can move past this.

Since we're not providing onKeyDown, hitting the `Enter` key will activate a button. If the button type is changed to "submit" it will submit a form. I think we should be good here! 👍 

You can investigate for yourself at http://storybook.operationcode.org/

**Comment by dirtyredz** [comment]
You can treat a button as a toggle to a screen read with the "aria-pressed" attribute.
Used specifically for situations like this (I think)
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#Toggle_buttons
