### ISSUE TITLE
Build a custom server

### ISSUE THREAD

**Issue by sethbergman** [OperationCode/front-end#238]
# Feature
## Why is this feature being added?

The custom server will be needed for juicy SEO benefits.

As it stands, we cant just throw files into static and have it be immediately routable on the server.

With a custom server, we can add routes that point to static files for crawlers (example: robots.txt)

[This issue explains further.](https://github.com/zeit/next.js/issues/226)

## What should your feature do?
Something similar to this in `<rootDir>/server.js`

*Warning*, do not copy-paste:
```javascript
const robotsOptions = {
  root: __dirname + '/static/',
  headers: {
    'Content-Type': 'text/plain;charset=UTF-8',
  }
};
server.get('/robots.txt', (req, res) => (
  res.status(200).sendFile('robots.txt', robotsOptions)
));

const sitemapOptions = {
  root: __dirname + '/static/',
  headers: {
    'Content-Type': 'text/xml;charset=UTF-8',
  }
};
server.get('/sitemap.xml', (req, res) => (
  res.status(200).sendFile('sitemap.xml', sitemapOptions)
));

const faviconOptions = {
  root: __dirname + '/static/'
};
server.get('/favicon.ico', (req, res) => (
  res.status(200).sendFile('favicon.ico', faviconOptions)
));
```

**Comment by ssiddhantsharma** [comment]
@sethbergman Any details! This seems kinda vague so I don't know how to approach your issue.

**Comment by sethbergman** [comment]
Sorry about that. I'll get the details up soon and get this moving. I've been working on another PR recently.

**Comment by sethbergman** [comment]
Thanks @kylemh I have been busy working at Dell. I made this issue before I started, and I'm going to open it up for other contributors. I apologise for the late response @dmarchante.

**Comment by wimo7083** [comment]
Okay adding things to this since it's still unclear. 

It looks like there are certain files we wish to be accessable at `/` route, some examples would be `robots.txt` or `favicon.ico` and `sitemap.xml`

we would like to place them in a single folder like `/static` or `/public` and just have them be sent in response to a request. 

Doing this within next (which I think is our routing solution) is not difficult but doesn't allow for any files in `/$some_dir` to be immediately accessed and then if that file is not found to use the normal next routing. 

I think the example @sethbergman brought up involves doing it automatically, but he's explicitly adding code for each case. 

So it could either be done to have it done automatically for any file in `/$some_dir` or have certain files explicitly defined.

**Comment by kylemh** [comment]
Updated comment

**Comment by kylemh** [comment]
@juliantrueflynn you'll wanna re-tackle this one. Please see https://github.com/OperationCode/front-end/pull/368
