### ISSUE TITLE
Implement non-blocking font loading

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#290]
# Feature request
**Is your feature request related to a problem? Please describe.**
We use @font-face which makes CSS part of the critical rendering path. We can improve our initial page load speed by address this problem.

**Describe the solution you'd like**
 [See this comment and thread for more details.](https://github.com/zeit/next.js/issues/512#issuecomment-322026199)

**Additional context**
Note that we're having to define fonts twice between Storybook and the application. If you can solve this - go ahead! Otherwise, just make worry about the app (not Storybook)

**Comment by nryoung** [comment]
@kylemh I think I will get my toes wet by grabbing this one. Assigning to myself.

**Comment by nryoung** [comment]
@kylemh I have been working on this, but I have a couple questions since I am pretty new to `@font-face`.

I have looked at the solution you have linked and I have implemented an HoC that is similar to what is detailed there.

Should I just be implementing this for google fonts, eg. `Encode Sans`, or should I do it for `DNI Condensed Bold` as well?

If I do have to do it for `DNI Condensed Bold` as well, I will have to modify the solution in the issue you linked since we are loading these locally.

It looks like I will need to add a special CSS class that I can add that will add all of the font classes once they are loaded, something along the lines of:
```
  document.documentElement.classList.add('fonts-loaded');
```
where the class looks like:
```
/* Class for async loaded fonts */
.fonts-loaded {
  font-family: Encode Sans, DIN Condensed Bold, sans-serif, serif;
}
```
Does that seem correct to you?

**Comment by nryoung** [comment]
> If I do have to do it for DNI Condensed Bold as well, I will have to modify the solution in the issue you linked since we are loading these locally.

I was did some more reading and I am actually incorrect about this. I just need to make sure to add a `@font-face` for `Encode Sans` in the CSS as well, since I don't see one now.

It also looks like adding CSS class like I mentioned above is the recommended way of doing this.
