### ISSUE TITLE
Conditionally render `login` and `join` views based upon auth

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#529]
# Feature request
Even when logged in, a user still sees the login and join items in the nav. Same with the `ReusableSections/JoinSection` component.

## Proposed solution
Conditionally render relevant items based upon when they're logged in. I recommend generating a list of spots you believe should be conditionally rendered, and confirming that list in this issue before writing code.

**Comment by AllenAnthes** [comment]
I'm thinking we check the user's loggedIn status in `_app.js`, filter out the `Who We Serve` section if they're already logged in, and pass the filtered list to  `Nav` through `Layout`, as well as `MobileNav`?

Also realized we're missing a logout option while doing this.

We could alternatively dispatch a redux action in `_app.js` for it, since the `Nav` component is already connected to the store.

Thoughts?

**Comment by kylemh** [comment]
I think it's very valid to have `isLoggedIn` as a variable in the redux store. We could then export a connected version of the JoinSection which conditionally renders based off of that fact. Plus handle nav stuff the way you mentioned.

**Comment by nvwebd** [comment]
What about something like this: https://kentcdodds.com/blog/authentication-in-react-applications ? I follow Kents work and he has some good blog posts / tuts / advice. I also implemented this - kinda similar auth rendering myself.

**Comment by kylemh** [comment]
We're not using hooks yet, so we can't just make a context hook like that. For what it's worth, what Allen proposed is very similar to how Kent would do it! Just with redux instead of context.

**Comment by kylemh** [comment]
Closed in #514
