### ISSUE TITLE
Use LogRocket Identify to better track repeat users' experiences

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#582]
# Feature request
LogRocket is cool.
Repeat users are cool.
Currently all users are anonymous.
Users could be tied to their login info so that we can gather repeat intel on repeat users helping us identify patterns (good and/or bad).

## Proposed solution
See example: ![Screen Shot 2019-06-10 at 12 10 12 AM](https://user-images.githubusercontent.com/9523719/59178560-2e114000-8b14-11e9-9215-5214b0891e36.png)

Probably integrate this as part of the login utility method.

**Comment by kylemh** [comment]
Blocked: https://github.com/OperationCode/back-end/issues/30

**Comment by kylemh** [comment]
https://github.com/OperationCode/back-end/issues/30

**Comment by juliantrueflynn** [comment]
We don't have to worry about any cross domain tracking, right? Everything is from operationcode.org?

**Comment by kylemh** [comment]
as long as `www` subdomain is caught too!

**Comment by hydrosquall** [comment]
Hi @kylemh, I'm interested in taking a pass at this. From looking at the comment, it looks like it's sufficient to generate an identifier based on concatenating IP Address with browser agent. Would that work for this project's purposes, or would you want additional types of metadata included as well?

**Comment by hydrosquall** [comment]
*Edit- Actually, while the User Agent can be easily pulled with javascript, the IP address still needs to be returned from an additional HTTP request. Does it seem feasible to have the login endpoint return the IP address from which the login request was made? If this ends up being more involved / isn't something you're looking to have someone from the outside handle (since it potentially touches PII, I'm also happy to leave it alone).
