### ISSUE TITLE
Create /resources page

### ISSUE THREAD

**Issue by jack-robs** [OperationCode/front-end#661]
# Feature request
Link for ResApi to front end, ResApi = project led by Aaron S. 

## Proposed solution
Hi All! Here is the first draft to the Resources Page. Let me know what you think. The idea is for the landing page to show the featured resources as default (not shown here) and then allowing users to select by either resource type (books, videos) and/or narrow search by typing specific key words on the search. They can also add new resources and up/down vote to help other users.  If you click on “New Resource” you can see the modal for adding one. Please note that the colors may be a little off because my computer’s colors are wacky for some reason, so focus on the usability, not so much the colors, please - they can always be changed.

## Mock
https://invis.io/SWRQZH0BP25#/360380181_Resources_Page

**Comment by jack-robs** [comment]
cc @aaron-suarez @kylemh

**Comment by kylemh** [comment]
Blocked by #448 and #447

**Comment by aaron-suarez** [comment]
We're in the process of adding a new endpoint to the Resources API for bulk creation of resources. If possible, we'd like the resource create form to have an options to add additional resources before clicking submit. @Brantron had a few comments regarding this:

>The easiest and fastest implementation would be to have an add another button to submit and clear the form if it receives a 200

>would also want to autofocus input #1 so if you have a bunch of these you can use tab and avoid the mouse

**Comment by Brantron** [comment]
I've done something like this before, the way we did it was to manually set a key on the component that held the form and it's state. Then when we got a 200 the key would change. This means the entire form, including internal state, was reset.

**Comment by kylemh** [comment]
@aaron-suarez if you have the fields you expect from a resource creation documented, I can create a ticket for the creation of _at least_ the single resource add form, and we could talk about bulk later.

**Comment by kylemh** [comment]
The Pagination and ResourceCard components exist now. All the components to create the mock exist, so we're unblocked 🎉

**Comment by hydrosquall** [comment]
Duplicating some notes from my PR description, I think there are plenty of other subtasks for this page in case any others who would like to work on this too.

Be warned that you can only fetch data from the server side in getInitialProps because of the access control headers on resources api, efforts to use the API from the clientside will just get you console warnings. Not sure if the current API URL is a temporary home or if it will eventually move alongside the other operationcode endpoints.

- I think separate components could be made for the filter buttons, new resource modal, unless we're OK with using some existing components from an existing design system
- Separate PRs could be made for adding text search, category filter, language filter, sorting, and price filter functionalities
- An overall style pass to fix the CSS grid layout for the card tiles (first for a fixed width, then to suit responsive screens). Currently the cards are flush against each other, I wanted to check if we have an existing grid layout system before doing something bootstrap-esque.

**Comment by kylemh** [comment]
That's actually the point of `getInitialProps`. It forces fetching to occur on the server. This is ideal for the resources page so that we can dynamically generate valuable metadata to improve our SEO.

Although, perhaps you only meant to highlight that client fetching isn't possible at all. Paging @aaron-suarez in regards to that.

Agreed completely on the PR being perfect as is. I'm not even really sure if all of the functionality is available regarding the filter buttons / inputs anyways...

I commented on the PR regarding styles!

**Comment by aaron-suarez** [comment]
@hydrosquall What needs to happen on the API side to allow for client fetching (or do we even want that?)

@kylemh I looked briefly at the PR, it seems we're missing the Algolia search bar (and the people from Algolia would certainly like to remind you it needs to say "Powered By Algolia" somewhere on the page.

Also, it looks like there's no way to navigate to it on the top bar. Maybe that should be a comment on the PR itself, but I think that's pretty necessary for discoverability and should absolutely be included in the MVP.

**Comment by hydrosquall** [comment]
@kylemh thanks for taking a look! I'll do a style fix after work.

@aaron-suarez 

> Also, it looks like there's no way to navigate to it on the top bar

My thought was to not add a navigation item until the page has some interaction capabilities. I was wondering how it's decided what links live in top vs bottom bar - for example, "history" is only in the footer but not the top bar.

I was thinking it would be good to prevent the page from being discoverable while it is "in progress". 

> it seems we're missing the Algolia search bar

I wanted to check if we had a search bar component that I had missed before coding up a new one or adding a dependency.

**Comment by aaron-suarez** [comment]
That's a good point. @kylemh we don't have a search bar component do we? Do we want to make an issue for that and get that PR in before we merge #918 ?

**Comment by kylemh** [comment]
We have a text input which can easily be made into a search bar! This is just a first-pass at the page. We won't be able to filter items unless the API is queryable via the client though...

**Comment by aaron-suarez** [comment]
Is it a CORS issue?

**Comment by kylemh** [comment]
Could be!

**Comment by hydrosquall** [comment]
Yep, it’s CORS. (I mixed it up with the other 4 letter security acronym
earlier, CSRF)

**Comment by hydrosquall** [comment]
I suppose we could do away with client side data fetching if every click
loads the whole page again using query parameters

https://stackoverflow.com/questions/43862600/how-to-get-query-string-parameters-from-url-in-next-js

**Comment by aaron-suarez** [comment]
Though I do somewhat like the idea of searches being shareable via a link... probably not for the MVP, but something to think about

**Comment by kylemh** [comment]
That will already be possible 👍

In terms of being RESTful, we'll be matching the browser URL up (query strings) to the filters being applied.

**Comment by chynh** [comment]
Hey all, just wondering if this issue is being taken care of. I have been working on this issue on my own and am close to putting together search bar and create resource component so let me know if additional help is needed.

**Comment by kylemh** [comment]
Feel free to keep working! We can resolve merge conflicts later.

**Comment by kylemh** [comment]
Resolved in #1100
